# Generated by Django 4.1.6 on 2023-02-15 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0003_fotografia_publicada"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="criada_em",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 15, 1, 55, 11, 512089)
            ),
        ),
    ]
