# Generated by Django 4.1.6 on 2023-02-15 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0004_fotografia_criada_em"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="criada_em",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 15, 15, 28, 49, 310239)
            ),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="foto",
            field=models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/"),
        ),
    ]
