# Generated by Django 4.1.6 on 2023-02-17 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0005_alter_fotografia_criada_em_alter_fotografia_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Nebulosa", "Nebulosa"),
                    ("Estrela", "Estrela"),
                    ("Galáxia", "Galáxia"),
                    ("Planeta", "Planeta"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="criada_em",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 17, 0, 45, 6, 350366)
            ),
        ),
    ]
